version: '3'


services:
    web-intotheanimus: 
        image: intotheanimus-nginx
        container_name: web-intotheanimus-nginx
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8001:80
        restart: unless-stopped